import { Hono } from "hono";
import type { Env } from "../types";
import { apiKeyRequired } from "../middleware/auth";

export const seed = new Hono<{ Bindings: Env }>();

// POST /api/admin/seed (API key required)
seed.post("/admin/seed", apiKeyRequired, async (c) => {
  const sampleEvents = [
    {
      id: "african-tech-summit-2025",
      short_code: "aTs25xKp",
      slug: "african-tech-summit-2025",
      title: "African Tech Summit 2025",
      description: "Join us for the biggest tech gathering in Zimbabwe! The African Tech Summit brings together innovators, entrepreneurs, investors, and tech enthusiasts from across the continent.\n\nThis year's theme: \"Building Africa's Digital Future\"\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "28",
      date_month: "Dec",
      date_full: "Saturday, December 28, 2025",
      date_time: "9:00 AM - 6:00 PM (CAT)",
      date_iso: "2025-12-28T09:00:00+02:00",
      location_venue: "Rainbow Towers Hotel",
      location_address: "Pennefather Ave",
      location_city: "Harare",
      location_country: "Zimbabwe",
      category: "Tech",
      tags: JSON.stringify(["startup", "innovation", "networking", "AI", "fintech", "sample"]),
      cover_image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
      attendee_count: 247,
      capacity: 500,
      host_name: "Zimbabwe Tech Hub",
      host_handle: "@zimtechhub",
      host_initials: "ZT",
      host_event_count: 12,
      price_amount: 25,
      price_currency: "USD",
      price_label: "Early Bird Ticket",
    },
    {
      id: "amapiano-night-nye",
      short_code: "nYe31vFx",
      slug: "amapiano-night-nye-edition",
      title: "Amapiano Night: NYE Edition",
      description: "Ring in the new year with the best Amapiano beats! Live DJs, great vibes, and an unforgettable night at Victoria Falls.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "31",
      date_month: "Dec",
      date_full: "Tuesday, December 31, 2025",
      date_time: "8:00 PM - 4:00 AM (CAT)",
      date_iso: "2025-12-31T20:00:00+02:00",
      location_venue: "The Venue",
      location_address: "Park Way Drive",
      location_city: "Victoria Falls",
      location_country: "Zimbabwe",
      category: "Music",
      tags: JSON.stringify(["amapiano", "nye", "party", "dj", "dance", "sample"]),
      cover_image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
      attendee_count: 89,
      capacity: 200,
      host_name: "Vic Falls Events",
      host_handle: "@vicfallsevents",
      host_initials: "VF",
      host_event_count: 24,
      price_amount: 50,
      price_currency: "USD",
      price_label: "General Admission",
    },
    {
      id: "sunrise-yoga-chivero",
      short_code: "yGa15hRm",
      slug: "sunrise-yoga-lake-chivero",
      title: "Sunrise Yoga at Lake Chivero",
      description: "Start your day with peace and tranquility. Join us for a sunrise yoga session overlooking the beautiful Lake Chivero. All levels welcome. Mats provided.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "15",
      date_month: "Jan",
      date_full: "Wednesday, January 15, 2025",
      date_time: "5:30 AM - 7:30 AM (CAT)",
      date_iso: "2025-01-15T05:30:00+02:00",
      location_venue: "Lake Chivero Recreational Park",
      location_address: "Lake Chivero",
      location_city: "Harare",
      location_country: "Zimbabwe",
      category: "Wellness",
      tags: JSON.stringify(["yoga", "meditation", "nature", "fitness", "mindfulness", "sample"]),
      cover_gradient: "linear-gradient(135deg, #4B0082, #004D40)",
      attendee_count: 32,
      capacity: 50,
      host_name: "Harare Wellness",
      host_handle: "@hararewellness",
      host_initials: "HW",
      host_event_count: 8,
    },
    {
      id: "startup-founders-meetup",
      short_code: "sFm24kLp",
      slug: "startup-founders-meetup-harare",
      title: "Startup Founders Meetup",
      description: "Connect with fellow founders, share your journey, and learn from each other. Casual networking in a relaxed environment. Refreshments provided.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "24",
      date_month: "Dec",
      date_full: "Tuesday, December 24, 2025",
      date_time: "6:00 PM - 9:00 PM (CAT)",
      date_iso: "2025-12-24T18:00:00+02:00",
      location_venue: "Impact Hub",
      location_address: "16 Cork Road, Avondale",
      location_city: "Harare",
      location_country: "Zimbabwe",
      category: "Professional",
      tags: JSON.stringify(["startup", "founders", "networking", "entrepreneurship", "sample"]),
      cover_gradient: "linear-gradient(135deg, #004D40, #00796B)",
      attendee_count: 45,
      capacity: 60,
      host_name: "Impact Hub Harare",
      host_handle: "@impactharare",
      host_initials: "IH",
      host_event_count: 32,
    },
    {
      id: "poetry-wine-evening",
      short_code: "pWe27bNx",
      slug: "poetry-wine-evening-book-cafe",
      title: "Poetry & Wine Evening",
      description: "An intimate evening of spoken word, poetry readings, and fine wine. Share your work or simply enjoy the art. Open mic available.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "27",
      date_month: "Dec",
      date_full: "Friday, December 27, 2025",
      date_time: "7:00 PM - 10:00 PM (CAT)",
      date_iso: "2025-12-27T19:00:00+02:00",
      location_venue: "Book Café",
      location_address: "Fife Avenue",
      location_city: "Harare",
      location_country: "Zimbabwe",
      category: "Culture",
      tags: JSON.stringify(["poetry", "spoken-word", "wine", "art", "literature", "sample"]),
      cover_gradient: "linear-gradient(135deg, #4B0082, #7B1FA2)",
      attendee_count: 28,
      capacity: 40,
      host_name: "Book Café",
      host_handle: "@bookcafeharare",
      host_initials: "BC",
      host_event_count: 56,
    },
    {
      id: "community-cleanup-borrowdale",
      short_code: "cCb28qWz",
      slug: "community-cleanup-borrowdale",
      title: "Community Clean-Up: Borrowdale",
      description: "Join your neighbors in keeping Borrowdale beautiful. Gloves and bags provided. Coffee and snacks after! Bring the whole family.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "28",
      date_month: "Dec",
      date_full: "Saturday, December 28, 2025",
      date_time: "7:00 AM - 11:00 AM (CAT)",
      date_iso: "2025-12-28T07:00:00+02:00",
      location_venue: "Borrowdale Park",
      location_address: "Borrowdale Road",
      location_city: "Harare",
      location_country: "Zimbabwe",
      category: "Community",
      tags: JSON.stringify(["volunteer", "environment", "cleanup", "community-service", "sample"]),
      cover_gradient: "linear-gradient(135deg, #5D4037, #8D6E63)",
      attendee_count: 67,
      capacity: 100,
      host_name: "Borrowdale Residents",
      host_handle: "@borrowdalera",
      host_initials: "BR",
      host_event_count: 6,
    },
    {
      id: "jozi-tech-meetup",
      short_code: "jTm15xRk",
      slug: "johannesburg-tech-meetup",
      title: "Joburg Tech & Startups Meetup",
      description: "Monthly gathering of Johannesburg's tech community. Lightning talks, networking, and drinks. All welcome!\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "20",
      date_month: "Jan",
      date_full: "Monday, January 20, 2025",
      date_time: "6:00 PM - 9:00 PM (SAST)",
      date_iso: "2025-01-20T18:00:00+02:00",
      location_venue: "Workshop17",
      location_address: "Sandton City",
      location_city: "Johannesburg",
      location_country: "South Africa",
      category: "Tech",
      tags: JSON.stringify(["startup", "tech", "networking", "south-africa", "sample"]),
      cover_gradient: "linear-gradient(135deg, #1a1a2e, #16213e)",
      attendee_count: 156,
      capacity: 200,
      host_name: "Jozi Tech Community",
      host_handle: "@jozitech",
      host_initials: "JT",
      host_event_count: 48,
    },
    {
      id: "nairobi-design-week",
      short_code: "nDw10pLm",
      slug: "nairobi-design-week-2025",
      title: "Nairobi Design Week 2025",
      description: "East Africa's largest design festival. Exhibitions, workshops, talks, and networking with creatives from across the continent.\n\n⚠️ This is sample data for demonstration purposes.",
      date_day: "10",
      date_month: "Feb",
      date_full: "Monday, February 10, 2025",
      date_time: "10:00 AM - 6:00 PM (EAT)",
      date_iso: "2025-02-10T10:00:00+03:00",
      location_venue: "Nairobi National Museum",
      location_address: "Museum Hill",
      location_city: "Nairobi",
      location_country: "Kenya",
      category: "Culture",
      tags: JSON.stringify(["design", "art", "exhibition", "creative", "kenya", "sample"]),
      cover_image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      attendee_count: 320,
      capacity: 500,
      host_name: "Nairobi Design Week",
      host_handle: "@nairobidesign",
      host_initials: "ND",
      host_event_count: 5,
      price_amount: 20,
      price_currency: "USD",
      price_label: "Day Pass",
    },
  ];

  let inserted = 0;
  let errors = 0;

  for (const event of sampleEvents) {
    try {
      await c.env.DB.prepare(`
        INSERT OR REPLACE INTO events (
          id, short_code, slug, title, description,
          date_day, date_month, date_full, date_time, date_iso,
          location_venue, location_address, location_city, location_country,
          category, tags, cover_image, cover_gradient,
          attendee_count, capacity, is_online,
          host_name, host_handle, host_initials, host_event_count,
          price_amount, price_currency, price_label
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).bind(
        event.id,
        event.short_code,
        event.slug,
        event.title,
        event.description,
        event.date_day,
        event.date_month,
        event.date_full,
        event.date_time,
        event.date_iso,
        event.location_venue,
        event.location_address,
        event.location_city,
        event.location_country,
        event.category,
        event.tags,
        (event as Record<string, unknown>).cover_image || null,
        (event as Record<string, unknown>).cover_gradient || null,
        event.attendee_count,
        event.capacity || null,
        false,
        event.host_name,
        event.host_handle,
        event.host_initials,
        event.host_event_count,
        (event as Record<string, unknown>).price_amount || null,
        (event as Record<string, unknown>).price_currency || null,
        (event as Record<string, unknown>).price_label || null
      ).run();
      inserted++;
    } catch (e) {
      console.error(`Error inserting ${event.id}:`, e);
      errors++;
    }
  }

  return c.json({
    message: "Sample data seeded successfully",
    inserted,
    errors,
    note: "All sample events are marked with 'sample' tag and disclaimer in description",
  });
});
