import { Hono } from "hono";
import type { Env } from "../types";
import { apiKeyRequired } from "../middleware/auth";

export const seed = new Hono<{ Bindings: Env }>();

// POST /api/admin/seed (API key required)
seed.post("/admin/seed", apiKeyRequired, async (c) => {
  const sampleEvents = [
    {
      _id: "african-tech-summit-2025",
      short_code: "aTs25xKp",
      slug: "african-tech-summit-2025",
      name: "African Tech Summit 2025",
      description: "Join us for the biggest tech gathering in Zimbabwe! The African Tech Summit brings together innovators, entrepreneurs, investors, and tech enthusiasts from across the continent.\n\nThis year's theme: \"Building Africa's Digital Future\"\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "28",
      date_display_month: "Dec",
      date_display_full: "Saturday, December 28, 2025",
      date_display_time: "9:00 AM - 6:00 PM (CAT)",
      start_date: "2025-12-28T09:00:00+02:00",
      location_name: "Rainbow Towers Hotel",
      location_street_address: "Pennefather Ave",
      location_locality: "Harare",
      location_country: "Zimbabwe",
      category: "Tech",
      keywords: JSON.stringify(["startup", "innovation", "networking", "AI", "fintech", "sample"]),
      image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
      attendee_count: 247,
      maximum_attendee_capacity: 500,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Zimbabwe Tech Hub",
      organizer_identifier: "@zimtechhub",
      organizer_initials: "ZT",
      organizer_alternate_name: null,
      organizer_event_count: 12,
      offer_price: 25,
      offer_price_currency: "USD",
      offer_url: null,
    },
    {
      _id: "amapiano-night-nye",
      short_code: "nYe31vFx",
      slug: "amapiano-night-nye-edition",
      name: "Amapiano Night: NYE Edition",
      description: "Ring in the new year with the best Amapiano beats! Live DJs, great vibes, and an unforgettable night at Victoria Falls.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "31",
      date_display_month: "Dec",
      date_display_full: "Tuesday, December 31, 2025",
      date_display_time: "8:00 PM - 4:00 AM (CAT)",
      start_date: "2025-12-31T20:00:00+02:00",
      location_name: "The Venue",
      location_street_address: "Park Way Drive",
      location_locality: "Victoria Falls",
      location_country: "Zimbabwe",
      category: "Music",
      keywords: JSON.stringify(["amapiano", "nye", "party", "dj", "dance", "sample"]),
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
      attendee_count: 89,
      maximum_attendee_capacity: 200,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Vic Falls Events",
      organizer_identifier: "@vicfallsevents",
      organizer_initials: "VF",
      organizer_alternate_name: null,
      organizer_event_count: 24,
      offer_price: 50,
      offer_price_currency: "USD",
      offer_url: null,
    },
    {
      _id: "sunrise-yoga-chivero",
      short_code: "yGa15hRm",
      slug: "sunrise-yoga-lake-chivero",
      name: "Sunrise Yoga at Lake Chivero",
      description: "Start your day with peace and tranquility. Join us for a sunrise yoga session overlooking the beautiful Lake Chivero. All levels welcome. Mats provided.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "15",
      date_display_month: "Jan",
      date_display_full: "Wednesday, January 15, 2025",
      date_display_time: "5:30 AM - 7:30 AM (CAT)",
      start_date: "2025-01-15T05:30:00+02:00",
      location_name: "Lake Chivero Recreational Park",
      location_street_address: "Lake Chivero",
      location_locality: "Harare",
      location_country: "Zimbabwe",
      category: "Wellness",
      keywords: JSON.stringify(["yoga", "meditation", "nature", "fitness", "mindfulness", "sample"]),
      cover_gradient: "linear-gradient(135deg, #4B0082, #004D40)",
      attendee_count: 32,
      maximum_attendee_capacity: 50,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Harare Wellness",
      organizer_identifier: "@hararewellness",
      organizer_initials: "HW",
      organizer_alternate_name: null,
      organizer_event_count: 8,
      offer_price: null,
      offer_price_currency: null,
      offer_url: null,
    },
    {
      _id: "startup-founders-meetup",
      short_code: "sFm24kLp",
      slug: "startup-founders-meetup-harare",
      name: "Startup Founders Meetup",
      description: "Connect with fellow founders, share your journey, and learn from each other. Casual networking in a relaxed environment. Refreshments provided.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "24",
      date_display_month: "Dec",
      date_display_full: "Tuesday, December 24, 2025",
      date_display_time: "6:00 PM - 9:00 PM (CAT)",
      start_date: "2025-12-24T18:00:00+02:00",
      location_name: "Impact Hub",
      location_street_address: "16 Cork Road, Avondale",
      location_locality: "Harare",
      location_country: "Zimbabwe",
      category: "Professional",
      keywords: JSON.stringify(["startup", "founders", "networking", "entrepreneurship", "sample"]),
      cover_gradient: "linear-gradient(135deg, #004D40, #00796B)",
      attendee_count: 45,
      maximum_attendee_capacity: 60,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Impact Hub Harare",
      organizer_identifier: "@impactharare",
      organizer_initials: "IH",
      organizer_alternate_name: null,
      organizer_event_count: 32,
      offer_price: null,
      offer_price_currency: null,
      offer_url: null,
    },
    {
      _id: "poetry-wine-evening",
      short_code: "pWe27bNx",
      slug: "poetry-wine-evening-book-cafe",
      name: "Poetry & Wine Evening",
      description: "An intimate evening of spoken word, poetry readings, and fine wine. Share your work or simply enjoy the art. Open mic available.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "27",
      date_display_month: "Dec",
      date_display_full: "Friday, December 27, 2025",
      date_display_time: "7:00 PM - 10:00 PM (CAT)",
      start_date: "2025-12-27T19:00:00+02:00",
      location_name: "Book Café",
      location_street_address: "Fife Avenue",
      location_locality: "Harare",
      location_country: "Zimbabwe",
      category: "Culture",
      keywords: JSON.stringify(["poetry", "spoken-word", "wine", "art", "literature", "sample"]),
      cover_gradient: "linear-gradient(135deg, #4B0082, #7B1FA2)",
      attendee_count: 28,
      maximum_attendee_capacity: 40,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Book Café",
      organizer_identifier: "@bookcafeharare",
      organizer_initials: "BC",
      organizer_alternate_name: null,
      organizer_event_count: 56,
      offer_price: null,
      offer_price_currency: null,
      offer_url: null,
    },
    {
      _id: "community-cleanup-borrowdale",
      short_code: "cCb28qWz",
      slug: "community-cleanup-borrowdale",
      name: "Community Clean-Up: Borrowdale",
      description: "Join your neighbors in keeping Borrowdale beautiful. Gloves and bags provided. Coffee and snacks after! Bring the whole family.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "28",
      date_display_month: "Dec",
      date_display_full: "Saturday, December 28, 2025",
      date_display_time: "7:00 AM - 11:00 AM (CAT)",
      start_date: "2025-12-28T07:00:00+02:00",
      location_name: "Borrowdale Park",
      location_street_address: "Borrowdale Road",
      location_locality: "Harare",
      location_country: "Zimbabwe",
      category: "Community",
      keywords: JSON.stringify(["volunteer", "environment", "cleanup", "community-service", "sample"]),
      cover_gradient: "linear-gradient(135deg, #5D4037, #8D6E63)",
      attendee_count: 67,
      maximum_attendee_capacity: 100,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Borrowdale Residents",
      organizer_identifier: "@borrowdalera",
      organizer_initials: "BR",
      organizer_alternate_name: null,
      organizer_event_count: 6,
      offer_price: null,
      offer_price_currency: null,
      offer_url: null,
    },
    {
      _id: "jozi-tech-meetup",
      short_code: "jTm15xRk",
      slug: "johannesburg-tech-meetup",
      name: "Joburg Tech & Startups Meetup",
      description: "Monthly gathering of Johannesburg's tech community. Lightning talks, networking, and drinks. All welcome!\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "20",
      date_display_month: "Jan",
      date_display_full: "Monday, January 20, 2025",
      date_display_time: "6:00 PM - 9:00 PM (SAST)",
      start_date: "2025-01-20T18:00:00+02:00",
      location_name: "Workshop17",
      location_street_address: "Sandton City",
      location_locality: "Johannesburg",
      location_country: "South Africa",
      category: "Tech",
      keywords: JSON.stringify(["startup", "tech", "networking", "south-africa", "sample"]),
      cover_gradient: "linear-gradient(135deg, #1a1a2e, #16213e)",
      attendee_count: 156,
      maximum_attendee_capacity: 200,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Jozi Tech Community",
      organizer_identifier: "@jozitech",
      organizer_initials: "JT",
      organizer_alternate_name: null,
      organizer_event_count: 48,
      offer_price: null,
      offer_price_currency: null,
      offer_url: null,
    },
    {
      _id: "nairobi-design-week",
      short_code: "nDw10pLm",
      slug: "nairobi-design-week-2025",
      name: "Nairobi Design Week 2025",
      description: "East Africa's largest design festival. Exhibitions, workshops, talks, and networking with creatives from across the continent.\n\n⚠️ This is sample data for demonstration purposes.",
      date_display_day: "10",
      date_display_month: "Feb",
      date_display_full: "Monday, February 10, 2025",
      date_display_time: "10:00 AM - 6:00 PM (EAT)",
      start_date: "2025-02-10T10:00:00+03:00",
      location_name: "Nairobi National Museum",
      location_street_address: "Museum Hill",
      location_locality: "Nairobi",
      location_country: "Kenya",
      category: "Culture",
      keywords: JSON.stringify(["design", "art", "exhibition", "creative", "kenya", "sample"]),
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      attendee_count: 320,
      maximum_attendee_capacity: 500,
      event_status: "EventScheduled",
      event_attendance_mode: "OfflineEventAttendanceMode",
      is_published: true,
      organizer_name: "Nairobi Design Week",
      organizer_identifier: "@nairobidesign",
      organizer_initials: "ND",
      organizer_alternate_name: null,
      organizer_event_count: 5,
      offer_price: 20,
      offer_price_currency: "USD",
      offer_url: null,
    },
  ];

  let inserted = 0;
  let errors = 0;

  for (const event of sampleEvents) {
    try {
      await c.env.DB.prepare(`
        INSERT OR REPLACE INTO events (
          _id, short_code, slug, name, description,
          date_display_day, date_display_month, date_display_full, date_display_time, start_date,
          location_name, location_street_address, location_locality, location_country,
          category, keywords, image, cover_gradient,
          attendee_count, maximum_attendee_capacity,
          event_status, event_attendance_mode, is_published,
          organizer_name, organizer_identifier, organizer_initials, organizer_alternate_name, organizer_event_count,
          offer_price, offer_price_currency, offer_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).bind(
        event._id,
        event.short_code,
        event.slug,
        event.name,
        event.description,
        event.date_display_day,
        event.date_display_month,
        event.date_display_full,
        event.date_display_time,
        event.start_date,
        event.location_name,
        event.location_street_address,
        event.location_locality,
        event.location_country,
        event.category,
        event.keywords,
        (event as Record<string, unknown>).image || null,
        (event as Record<string, unknown>).cover_gradient || null,
        event.attendee_count,
        event.maximum_attendee_capacity,
        event.event_status,
        event.event_attendance_mode,
        event.is_published,
        event.organizer_name,
        event.organizer_identifier,
        event.organizer_initials,
        event.organizer_alternate_name,
        event.organizer_event_count,
        event.offer_price,
        event.offer_price_currency,
        event.offer_url
      ).run();
      inserted++;
    } catch (e) {
      console.error(`Error inserting ${event._id}:`, e);
      errors++;
    }
  }

  return c.json({
    message: "Sample data seeded successfully",
    inserted,
    errors,
    note: "All sample events are marked with 'sample' tag and disclaimer in description",
  });
});
