-- Seed categories into the database
-- These were previously hardcoded in the application code

INSERT OR IGNORE INTO categories (id, name, group_name, sort_order) VALUES
  ('tech', 'Technology', 'Technology & Innovation', 0),
  ('ai-ml', 'AI & Machine Learning', 'Technology & Innovation', 1),
  ('fintech', 'Fintech', 'Technology & Innovation', 2),
  ('crypto', 'Crypto & Web3', 'Technology & Innovation', 3),
  ('business', 'Business', 'Business & Economy', 4),
  ('economy', 'Economy', 'Business & Economy', 5),
  ('investment', 'Investment', 'Business & Economy', 6),
  ('real-estate', 'Real Estate', 'Business & Economy', 7),
  ('music', 'Music', 'Entertainment & Media', 8),
  ('film-tv', 'Film & TV', 'Entertainment & Media', 9),
  ('gaming', 'Gaming', 'Entertainment & Media', 10),
  ('celebrity', 'Celebrity & Entertainment', 'Entertainment & Media', 11),
  ('football', 'Football', 'Sports', 12),
  ('sports-other', 'Other Sports', 'Sports', 13),
  ('fitness', 'Fitness & Wellness', 'Sports', 14),
  ('culture', 'Culture & Society', 'Culture & Society', 15),
  ('fashion', 'Fashion', 'Culture & Society', 16),
  ('food', 'Food & Drink', 'Culture & Society', 17),
  ('travel', 'Travel', 'Culture & Society', 18),
  ('politics', 'Politics', 'News & Current Affairs', 19),
  ('world-news', 'World News', 'News & Current Affairs', 20),
  ('local-news', 'Local News', 'News & Current Affairs', 21),
  ('education', 'Education', 'Education & Knowledge', 22),
  ('science', 'Science', 'Education & Knowledge', 23),
  ('history', 'History', 'Education & Knowledge', 24),
  ('relationships', 'Relationships', 'Lifestyle', 25),
  ('parenting', 'Parenting', 'Lifestyle', 26),
  ('spirituality', 'Spirituality', 'Lifestyle', 27),
  ('art', 'Art', 'Creative Arts', 28),
  ('literature', 'Literature', 'Creative Arts', 29),
  ('comedy', 'Comedy', 'Creative Arts', 30),
  ('environment', 'Environment', 'Environment', 31);
